#!/bin/bash

f=.gitrepos
ignore_f=.gitignore
mode="init"

if [ "$1" ]; then
  mode=$1
fi

if [ "$2" ]; then
  f=$2
fi

if [ -f $f ];then
  while read -a p; do
    len=${#p[@]}
    if [ $len -gt 1 ];then
      d=${p[$len-1]}
      if [ "$mode" = "init" ];then
        if [ -d $d ];then
          (echo $d; cd $d; git pull)
        else
          git clone ${p[@]}
        fi

        git check-ignore $d >/dev/null
        if [ $? -eq 1 ];then
          echo "/$d" >> $ignore_f
        fi

      elif [ "$mode" = "clean" ];then
        rm -r $d

      elif [ "$mode" = "status" ];then
        echo $d
        if [ -d $d ];then
          (cd $d; git status)
        else
          echo "Not initialized"
        fi
        echo
      fi
    fi
  done <$f
else
  echo "$f not exist"
fi
